[package]
name = "puzzgen"
description = "Generate a jigsaw puzzle"
version = "0.1.0"
authors = ["George Madrid <gmadrid@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
env_logger = "0.6.0"
error-chain = "0.12.0"
rand = "0.6.5"
